SaasOvation\IdentityAccess\Domain\Model\Identity\UserPasswordChanged:
    expose_policy: NONE

    properties:
        tenantId:
            type: SaasOvation\IdentityAccess\Domain\Model\Identity\TenantId

        username:
            type: string

        eventVersion:
            type: integer

        occurredOn:
            type: DateTime