SaasOvation\Common\Domain\Model\Process\TimeConstrainedProcessTracker:
    type: entity
    table: tbl_time_constrained_process_tracker

    id:
        timeConstrainedProcessTrackerId:
            type: integer
            generator:
                strategy: AUTO

    embedded:
        processId:
            class: SaasOvation\Common\Domain\Model\Process\ProcessId

    fields:
        concurrency_version:
            type: integer

        allowableDuration:
            type: integer

        completed:
            type: boolean

        description:
            type: string

        processInformedOfTimeout:
            type: boolean

        processTimedOutEventType:
            type: string

        retryCount:
            type: integer

        tenantId:
            type: string

        timeoutOccursOn:
            type: integer

        totalRetriesPermitted:
            type: integer