SaasOvation\Common\Event\StoredEvent:
    type: entity
    table: tbl_stored_event

    id:
        eventId:
            column: event_id
            type: integer
            generator:
                strategy: AUTO

    fields:
        eventBody:
            column: event_body
            type: string

        occurredOn:
            column: occurred_on
            type: datetime

        typeName:
            column: type_name
            type: string